<div class="content-wrapper" ng-app="app" ng-controller="productController">
    <section class="content-header">
        <h1> Manage Merchant</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Systems setup</a></li>
            <li class="active"> Manage Merchant</li>
        </ol>
    </section>
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title"> Manage Product</h3>
                        <div class="pull-right"> 
                            &nbsp;<a href="<?php echo $this->basePath() ?>/merchant/product/getproductlist?download_csv=download_csv" class="btn btn-info"> Download Product Csv</a>
                            &nbsp;<a href="<?php echo $this->basePath() ?>/merchant/product/exportcsv" class="btn btn-info"> export Own Product</a>
                        </div>                        
                    </div>
                    <!-- /.box-header -->
                     <!-- /.box-header -->
                    <div class="col-sm-10 col-lg-10  no-rpad">
                        <label class="ml10">Search By</label></div>
                    <div class="col-sm-10 col-lg-10  no-rpad">
                    <form name="searchLogFrm" id="searchLogFrm" ng-submit="querySearch()" class="ng-valid ng-dirty ng-valid-parse ng-submitted"> 
                    <div class="alert alert-danger alert-dismissable col-md-12 ng-binding ng-hide" ng-show="errorStatus">{{errorMsg}}</div>
                    <div class="full-width fl">
                        <div class="input-group">
                            <div class="input-group-btn">
                                <button id="filtertypeofbutton" type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-expanded="false">{{selected_filter_level}}<span class="caret"></span></button>
                                <ul class="dropdown-menu pos-absolute" role="menu" id="filtertypeof">
                                        <li><a href="javascript:void(0);" data-type="name" ng-click="setFilterType('Product_name')">Product Name</a></li>
                                        <li><a href="javascript:void(0);" data-type="email" ng-click="setFilterType('Attribute_name')">Attribute Name</a></li>
                                        <li><a href="javascript:void(0);" data-type="phone" ng-click="setFilterType('Category_name')">Category Name</a></li>
                                </ul>
                            </div>

                            <input ng-model="filterText" type="text" class="form-control search-input ng-valid ng-touched ng-dirty ng-valid-parse" aria-label="..." placeholder="Search {{selected_filter_level}}" value="">
                            
                        </div>  
                    </div>   
                    </form>
                    </div>
                    <div class="col-sm-2 no-lpad">
                        <a href="#" ng-click="refresh()"><i class="fa fa-refresh" aria-hidden="true" ></i></a>
                        <button class="btn btn-default pull-right" type="button"  ng-click="querySearch()"id="show-attribute"><i class="fa fa-align-left"></i> Search Filter</button>
                    </div>
                     
                    <div class="box-body">
                        <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                            <div class="row">
                                <div class="col-sm-6"></div>
                                <div class="col-sm-6"></div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <table class="table table-bordered table-hover dataTable" id="example2" role="grid" aria-describedby="example2_info">
                                        <thead>
                                            <tr role="row">
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending">Product Name</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Category Name</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Product Description</th>                                                
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr role="row" ng-repeat="(key, product) in productList">
                                                <td class="">{{product.product_name}}</td>
                                                <td class="">{{product.category_name}}</td>
                                                <td class="">{{product.product_desc}}</td>
                                                <td class="">
                                                    <div class="pull-right"> 
                                                        <a href="<?php echo $this->basePath() ?>/merchant/product/inventry?id={{product.id}}" class="btn btn-info">Manage Inventry</a>
                                                    </div>                                                    
                                                </td>
                                            </tr>
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                </div>
                                <div class="col-sm-8">
                                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                                        <pagination  class="pagination pull-right mt0" ng-model="currentPage" total-items="numberOfRecord" max-size="3" boundary-links="true" ng-click="selectPage(currentPage)"></pagination>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>
    </section>
    <div style="position: fixed; top: 0; left: 0; background: rgba(0,0,0,0.3); z-index: 99999999; width: 100%; height: 100%;"  ng-show="ajaxLoadingData">
        <img style="position: absolute; top: 40%; left: 45%; width: 250px; " alt="loader" src="<?=$this->basePath()?>/public/img/loading_cart.gif">
    </div>
</div>
<script>
    var app = angular.module('app', ['ui.bootstrap']);
</script>
<script src="<?php echo $this->basePath() . '/public/js/merchant/dashboard/product.js' ?>"></script>

