<div class="content-wrapper">
    <section class="content-header">
        <h1> Product Out Of Stock</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Systems setup</a></li>
            <li class="active"> Product Out Of Stock</li>
        </ol>
    </section>
    <section class="content container-fluid">
        <div class="row" ng-app="product" ng-controller="productOutOfStock" ng-cloak="true">
            <div class="col-xs-12">
                <div class="box">
                    <div class="col-sm-10 col-lg-10  no-rpad">
                    </div>
                    <div class="clearfix"></div>

                    <div class="box-body">                       
                        <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                            <div class="row">
                                <div class="col-sm-6"></div>
                                <div class="col-sm-6"></div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <table class="table table-bordered table-hover dataTable" id="example2" role="grid" aria-describedby="example2_info">
                                        <thead>
                                            <tr role="row">
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending">Product Name</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Attribute Name</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Attribute Unit</th>
                                                <th class="sorting_desc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" aria-sort="descending">Attribute quantity</th>
                                                <th class="sorting_desc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" aria-sort="descending">Product In Stock</th>
                                                <th class="sorting_desc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" aria-sort="descending">Store Name</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr role="row" class="odd" ng-repeat="data in productList">
                                                <td class=""><i class="fa fa-close red"></i> &nbsp;{{data.product_name}}</td>
                                                <td class="">{{data.name}}</td>
                                                <td class="">{{data.unit}}</td>
                                                <td class="sorting_1">{{data.quantity}}</td>
                                                <td class="sorting_1">{{data.stock}}</td>
                                                <td class="sorting_1">{{data.store_name}}</td>
                                                <td>
                                                    <a href="<?php echo $this->basePath()?>/merchant/product/inventry?id={{data.product_id}}"><i class="fa fa-edit"></i> </a>
                                                </td>
                                            </tr>
                                            
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Total {{numberOfRecord}} entries</div>
                                </div>
                                <div class="col-sm-8">
                                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                                        <pagination  class="pagination pull-right mt0" ng-model="currentPage" total-items="numberOfRecord" max-size="5" boundary-links="true" ng-click="selectPage(currentPage)"></pagination>
                                    </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>
    </section>
</div>

<script src="<?php echo $this->basePath() . '/public/js/merchant/dashboard/outofstock.js' ?>"></script>
<script>
var PAGE_COUNT = 5;
var PAGING_GAP = 3;  
</script>