<div class="content-wrapper" ng-app="app" ng-controller="storeController">
    <section class="content-header">
        <h1> Manage Store</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Systems Store</a></li>
            <li class="active"> Manage Store</li>
        </ol>
    </section>
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title"> Manage Store</h3>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body">
                        <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                            <div class="row">
                                <div class="col-sm-6"></div>
                                <div class="col-sm-6"></div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <table class="table table-bordered table-hover dataTable" id="example2" role="grid" aria-describedby="example2_info">
                                        <thead>
                                            <tr role="row">
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending">Product name</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Attribute</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending">Quantity</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Price</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending">Stock In</th>
                                            </tr>
                                        </thead>
                                        <tbody>    
                                            <tr role="row" class="odd" ng-repeat="data in storeList">
                                                        <td class="">{{data.product_name}}</td>
                                                        <td class="">{{data.name}}</td>
                                                        <td class="">{{data.quantity}}</td>
                                                        <td class="">{{data.price}}</td>
                                                        <td class="">{{data.stock}}</td>
                                                    </tr>
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                            <div class="row">
                            <div class="col-sm-4">
                                <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Total {{numberOfRecord}} entries</div>
                            </div>
                            <div class="col-sm-8">
                                <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                                    <pagination  class="pagination pull-right mt0" ng-model="currentPage" total-items="numberOfRecord" max-size="3" boundary-links="true" ng-click="selectPage(currentPage)"></pagination>
                                </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>
    </section>
</div>
<script>
    var PAGE_COUNT = 5;
    var PAGING_GAP = 3;
    var app = angular.module('app', ['ui.bootstrap']);
</script>
<script src="<?php echo $this->basePath() . '/public/js/merchant/dashboard/storein.js' ?>"></script>

