 <body class="hold-transition skin-blue sidebar-mini">
        <div class="wrapper">
            <!-- Main Header -->
            <header class="main-header">
                <!-- Logo -->
                <a href="<?= $GLOBALS['HTTP_SITE_ADMIN_URL'] ?>" class="logo">
                    <!-- mini logo for sidebar mini 50x50 pixels -->
                    <span class="logo-mini"><img src="<?= $this->basePath() ?>/public/css/dist/img/logo-mini.png" class="" alt="Logo"></span>
                    <!-- logo for regular state and mobile devices -->
                    <span class="logo-lg"><img src="<?= $this->basePath() ?>/public/css/dist/img/logo.png" class="" alt="Logo"></span> </a>
                <!-- Header Navbar -->
                <nav class="navbar navbar-static-top" role="navigation">
                    <!-- Sidebar toggle button-->
                    <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button"> <span class="sr-only">Toggle navigation</span> </a>
                    <!-- Navbar Right Menu -->
                    <div class="navbar-custom-menu">
                        <ul class="nav navbar-nav">
                            <!-- Messages: style can be found in dropdown.less-->
                            <!-- /.messages-menu -->
                            <!-- Notifications Menu -->
                            <li class="dropdown notifications-menu" onclick="updateNotification('admin')">
                                <!-- Menu toggle button -->
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="fa fa-bell-o"></i> <span class="label label-warning"><none id="notificaiton_count"></none></span> </a>
                                <ul class="dropdown-menu">
                                    <li>
                                        <!-- Inner Menu: contains the notifications -->
                                        <ul class="menu" id="notificationList">
                                            <li> </li>
                                        </ul>
                                    </li>
                                    <li class="footer"><a href="#">View all</a></li>
                                </ul>
                            </li>
                            <!-- User Account Menu -->
                            <li class="dropdown user user-menu">
                                <!-- Menu Toggle Button -->
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <!-- The user image in the navbar-->
                                    <img src="<?= $this->basePath() ?>/public/css/dist/img/avatar04.png" class="user-image" alt="User Image">
                                    <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                    <span class="hidden-xs"><?php echo $GLOBALS['user']['data'][0]['first_name']; ?></span> </a>
                                <ul class="dropdown-menu">
                                    <!-- The user image in the menu -->
                                    <li class="user-header"> <img src="<?= $this->basePath() ?>/public/css/dist/img/avatar04.png" class="img-circle" alt="User Image">
                                    </li>
                                    <!-- Menu Body -->
                                    <!-- Menu Footer-->
                                    <li class="user-footer">
                                        <div class="pull-left"> <a href="#" class="btn btn-default btn-flat">Profile</a> </div>
                                        <div class="pull-right"> <a href="<?= $GLOBALS['HTTP_SITE_ADMIN_URL'] ?>common/logout" class="btn btn-default btn-flat">Sign out</a> </div>
                                    </li>
                                </ul>
                            </li>
                            <!-- Control Sidebar Toggle Button -->
                            <li class="hide"> <a href="#" data-toggle="control-sidebar"><i class="fa fa-gears"></i></a> </li>
                        </ul>
                    </div>
                </nav>
            </header>    
            <?php
            echo $this->partial('admin/partial/leftMenu.phtml');
            ?>    
            <script>
                var serverAppUrl = '<?php echo $GLOBALS['SITE_APP_URL']; ?>';
                var serverAdminApp = '<?php echo $GLOBALS['HTTP_SITE_ADMIN_URL']; ?>';
            </script>
