<div class="content-wrapper" ng-app="app" ng-controller="managebanner"  ng-cloak="true">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1> Add Category</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Manage Banner</a></li>
            <li class="active"> Add Banner</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <!-- /.box-header -->
                    <div class="box-body">
                        <p class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</p>
                        <p class="danger" style="color:green" ng-show="successShow">{{successMsg}}</p>
                        <div class="row">
                            <div class="col-lg-4 col-sm-4 col-xs-12">
                                <div class="box-header">
                                    <h3 class="box-title"> Add Banner</h3>
                                    <p>Add Banner for product</p>
                                </div>
                            </div>
                            <div class="col-lg-8 col-sm-8 col-xs-12">
                                <div class="row">
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Enter Redirect Link</label>
                                            <input type="text" class="form-control" name="description" ng-model="bannerData.link">
                                            <!-- /.input group -->
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <label>Category Image</label>
                                        <input type="file" id="uploadfile"  ng-model="upload_file" onchange="uploadImageInTemp(this)">
                                        <input type="hidden" id="banner_img">
                                        <input type="hidden" id="image_name">
                                    </div>
                                    <div class="clearfix"></div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Description</label>
                                            <textarea class="form-control" name="description" ng-model="bannerData.description"> </textarea>
                                            <!-- /.input group -->
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Product Status</label>
                                            <div class="clearfix"></div>
                                            <label class="mr10">Active</label>					
                                            <input type="radio" name="status" value="1" ng-model="bannerData.status" class="minimal">

                                            <label class="mr10 ml10">Inactive</label>					
                                            <input type="radio" name="status" value="0" class="minimal" ng-model="bannerData.status">
                                        </div>  
                                    </div>    
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="pull-right">
                            <a href="<?php echo $this->basePath() ?>/admin/dashboard/managebanner" class="btn btn-info"> Cancel</a>
                            <button class="btn btn-info" ng-click="savebanner(bannerData)">Save</button>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
<script>
    var app = angular.module('app', []);
    app.value('bannerData', <?=json_encode($this->bannerData)?>);
</script>
<script src="<?php echo $this->basePath() . '/public/js/dashboard/managebanner.js' ?>">
</script>
