<div class="content-wrapper" ng-app="app" id="managelocation" ng-controller="managecity"  ng-cloak="true">
    <!-- Content Header (Page header) -->
    
    <section class="content-header">
        <h1> Add City</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Manage City</a></li>
            <li class="active"> Add City</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <!-- /.box-header -->
                    <div class="box-body">
                        <p class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</p>
                        <p class="danger" style="color:green" ng-show="successShow">{{successMsg}}</p>
                        <div class="row">
                            <div class="col-lg-4 col-sm-4 col-xs-12">
                                <div class="box-header">
                                    <h3 class="box-title">Area City</h3>
                                </div>
                            </div>
                            <div class="col-lg-8 col-sm-8 col-xs-12">
                                <div class="row">
                                   
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Select Country</label>
                                            <select class="form-control select2" ng-change="getCity(cityData.country_id)" style="width: 100%;" ng-model="cityData.country_id">
                                                <option value="0">Select Country</option>
                                                <option  ng-repeat="country in countrylist" ng-selected="country.id == country_id" value="{{country.id}}">{{country.country_name}}</option>
                                            </select>
                                        </div>
                                    </div> 
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>City</label>
                                            <input type="text" placeholder="City" class="form-control"  name="name"   ng-model="cityData.city_name">
                                        </div>
                                    </div>
                                                                  
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="pull-right">
                            <a href="<?php echo $this->basePath() ?>/admin/dashboard/managecity" class="btn btn-info"> Cancel</a>
                            <button class="btn btn-info" ng-click="saveCity(cityData)">Save</button>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
 <script>
    var app = angular.module('app', []);
    app.value('cityList', <?php echo !empty($this->cityList)?json_encode($this->cityList):'';?>);
</script>
<script src="<?php echo $this->basePath() . '/public/js/dashboard/managecity.js' ?>">
</script>