<div class="content-wrapper" ng-app="app" ng-controller="managetax"  ng-cloak="true">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1> Add Tax</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Manage Tax</a></li>
            <li class="active"> Add Tax</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <!-- /.box-header -->
                    <div class="box-body">
                        <p class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</p>
                        <p class="danger" style="color:green" ng-show="successShow">{{successMsg}}</p>
                        <div class="row">
                            <div class="col-lg-4 col-sm-4 col-xs-12">
                                <div class="box-header">
                                    <h3 class="box-title"> Add Tax</h3>
                                    <p>Add tax for product</p>
                                </div>
                            </div>
                            <div class="col-lg-8 col-sm-8 col-xs-12">
                                <div class="row">
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Tax Name</label>
                                            <input type="text" placeholder="Tax Name" class="form-control"  name="name"   ng-model="taxData.tax_name">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Tax Vale in %</label>
                                            <input type="text" placeholder="Tax value" class="form-control"  name="name"   ng-model="taxData.tax_value">
                                        </div>
                                    </div>
                                    
                                    
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="pull-right">
                            <a href="<?php echo $this->basePath() ?>/admin/dashboard/managetax" class="btn btn-info"> Cancel</a>
                            <button class="btn btn-info" ng-click="savetax(taxData)">Save</button>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
<script src="<?php echo $this->basePath() . '/public/js/dashboard/managetax.js' ?>">
</script>
<script>
    
    app.value('taxList', '<?php echo !empty($this->taxList)?json_encode($this->taxList):'';?>');
</script>