<?php
/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
?>
<form onsubmit="return validateFormData('addUserForm');" id="addUserForm" method="post" action="<?php echo $GLOBALS['HTTP_SITE_ADMIN_URL']."dashboard/usersaveAction"?>">
    <select id="status" name="status" validation="blank" title="Status">
        <option value="1">Enable</option>
        <option value="0">Disable</option>
    </select>
    <br>First name:
    <input type="text" id="fname" name="name" validation="blank" title="Name" >
    </br> First name:
    <input type="text" id="password" name="password" validation="blank" title="Password">
    </br><br>Last name:<input type="text" id="email" name="email" validation="email" title="Email">
    </br><br>Email:<input type="text" id="mobilenumber" name="mobilenumber" validation="mobileNumber" title="Phone Number" >
   </br><br>User name: <input type="text" id="country" name="country" validation="blank" title="Country" >
    </br><br>Password: <input type="text" id="state" name="state" validation="blank" title="state" >
    </br><br>Confirm Password: <input type="text" id="city" name="city" validation="blank" title="City">
   </br> <br>Email: <input type="text" id="pincode" name="pincode" validation="blank" title="Pin Code">
   </br> <br>Email Password: <textarea id="address" name="address" validation="blank" title="Address" ></textarea>
   <input type="submit" value="save"/>
</form>