<ul>
    <?php
    foreach($this->countryList as $country){
        echo "<li> $country[country_name]</li>";
    }
    ?>
</ul>

<h2>Country List</h2>                                                                                     
  <div class="table-responsive">          
  <table class="table table-hover table-condensed">
    <thead>
      <tr>
        <th>Countries</th>
        
      </tr>
    </thead>
    <tbody>
      <tr ng-repeat="dataList in templateList" class="templateList">
                        <td>{{index+1}}</td>
                        
                    </tr>
    </tbody>
  </table>
  </div>