<div class="content-wrapper" ng-app="marchantapp" ng-controller="marchantController"  ng-cloak="true">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1> Add Product</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Manage marchant</a></li>
            <li class="active"> Edit Marchant</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <!-- /.box-header -->
                    <div class="box-body">
                        <p class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</p>
                        <p class="danger" style="color:green" ng-show="successShow">{{successMsg}}</p>
                        <div class="row">
                            <div class="col-lg-4 col-sm-4 col-xs-12">
                                <div class="box-header">
                                    <h3 class="box-title"> Edit Marchant</h3>
                                </div>
                            </div>
                            <div class="col-lg-8 col-sm-8 col-xs-12">
                                <div class="row">
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Owner Name</label>
                                            <input type="text" placeholder=" Name" class="form-control"  name="name"   ng-model="marchantData.name">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Ic Number</label>
                                            <input type="text" placeholder="Ic Number" class="form-control"  name="name"   ng-model="marchantData.ic_number">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Phone Number</label>
                                            <input type="text" placeholder="Phone Number" class="form-control"  name="name"   ng-model="marchantData.phone_number">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Email</label>
                                            <input type="email" placeholder="email" class="form-control"  name="name"   ng-model="marchantData.email">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Address</label>
                                            <input type="text" placeholder="Address" class="form-control"  name="name"   ng-model="marchantData.address">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <label>Merchant Image</label>
                                        <input type="file" id="uploadfile"  ng-model="upload_file" onchange="uploadImageInTemp(this)">
                                        <input type="hidden" id="merchant_img">
                                    </div>                                    
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Company Bank Name </label>
                                            <input type="text" placeholder="Company Bank Name" class="form-control"  name="name"   ng-model="marchantData.bank_name">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Company Bank Account Number</label>
                                            <input type="text" placeholder="Company Bank Account Number" class="form-control"  name="name"   ng-model="marchantData.bank_account_number">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-12 col-xs-12">
                                        <div class="form-group">
                                            <label>Status</label>
                                            <div class="clearfix"></div>
                                            <label class="mr10">Active</label>					
                                            <input type="radio" name="r1" value="1" class="minimal"  ng-model="marchantData.status">

                                            <label class="mr10 ml10">Inactive</label>					
                                            <input type="radio" name="r1" class="minimal" value="0"  ng-model="marchantData.status">
                                        </div>
                                    </div> 
                                    
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="pull-right">
                            <a href="<?php echo $this->basePath() ?>/admin/dashboard/managemerchant" class="btn btn-info"> Cancel</a>
                            <button class="btn btn-info" ng-click="savemerchant()">Save</button>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
<script>
    var app = angular.module('marchantapp', []);    
    app.value('marchantList', '<?php echo !empty($this->marchantData)?json_encode($this->marchantData):'';?>');
</script>
<script src="<?php echo $this->basePath() . '/public/js/dashboard/managemarchant.js' ?>">
</script>
