<html>
    <body ng-app="emailSetup">
        <div ng-controller="emailSetupController">
            <table align="center" cellpadding="6">
                <tr>
                    <td colspan="1"><span ng-show="successMsg" id="success_msg" style="color:green">{{succe}}</span></td>
                    <td colspan="1"><span ng-show="errorMsg" id="success_error" style="color:red">{{errCode}}</span></td>
                </tr>
                <tr>
                    <td>Type :</td>
                <td>
                    <select class="col-md-10" ng-model="mailType" ng-change="changeMailtype()" required>
                        <option value="">Select One</option>
                        <option ng-repeat="typeDetails in typeArr" value="{{typeDetails.id}}">{{typeDetails.name}}</option>
                    </select> <span style="color:red"> *</span>
                    
                </td>
                </tr>
                <tr>
                <td>Nick Name :</td>
                <td>
                    <input class="col-md-10" type="text" name="nick_name" id="nick_name" ng-model="nickName" placeholder="Nick Name" required> <span style="color:red"> *</span>
                </td>
                </tr>
                <tr>
                <td>Subject :</td>
                <td>
                    <input class="col-md-10" type="text" name="subject" id="subject" ng-model="subject" value="{{mailType}}" required> <span style="color:red"> *</span>
                </td>
                </tr>
                <tr>
                <td>CC :</td>
                <td>
                    <input class="col-md-10" type="text" name="cc_mail" id="cc_mail" ng-model="ccMail" placeholder="CC Mail"">
                </td>
                </tr>
                <tr>
                <td>BCC :</td>
                <td>
                    <input class="col-md-10" type="text" name="bcc_mail" id="bcc_mail" ng-model="bccMail" placeholder="Bcc Mail ">
                </td>
                </tr>
                <tr>
                <td>Body</td>    
                <td>
                    <textarea class="col-md-10" ng-model="bodymsg"  id="articleContent" name="articleContent">
                        
                    </textarea>
                </td>
                </tr>
                <tr>  
                <td>
                <input type="submit" value="Preview" name="preview" ng-click="emailPreview">
                </td>
                <td>
                  <input type="submit" value="Submit" name="Submit" ng-click="emailSumbit()">
                </td>
                </tr>
                <tr>
            </table>
        </div>
    </body>    
</html>
    <script src="/hireapplicants/public/js/email/emailsetup.js"></script>  
    <script type="text/javascript" src="/hireapplicants/public/js/ckeditor/ckeditor.js"></script>
    <script type="text/javascript">
        CKEDITOR.replace( 'articleContent' );
    </script> 
                    
