<div class="content-wrapper">
<section class="content-header">
      <h1> Area Locatin</h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Systems setup</a></li>
        <li class="active"> Manage Area Locaiton</li>
      </ol>
    </section>
<section class="content container-fluid">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title"> Manage Area Locaiton</h3>
              <div class="pull-right"> 
                  <a href="<?php echo $this->basePath()?>/admin/dashboard/addlocation" class="btn btn-info"> Add Location Area</a>
              </div>              
            </div>
            <!-- /.box-header -->
            <div class="box-body">
              <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                <div class="row">
                  <div class="col-sm-6"></div>
                  <div class="col-sm-6"></div>
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    <table class="table table-bordered table-hover dataTable" id="example2" role="grid" aria-describedby="example2_info">
                      <thead>
                        <tr role="row">
                          <th class="sorting">Address</th>
                          <th class="sorting">google Address</th>
                          <th class="sorting">Action</th>
                        </tr>
                      </thead>
                      <tbody>
                          <?php if(!empty($this->locationListData)){
                            foreach ($this->locationListData as $key => $value) {
                              ?>
                            <tr role="row" class="odd">
                                <td class=""><?php if(empty($value['active'])){?><i class="fa fa-close red"></i> &nbsp;<?php } ?><?= $value['address']?></td>
                              <td class=""><?= $value['googlelocation']?></td>
                              <td>
                                  <a href="<?= $this->basePath()?>/admin/dashboard/addlocation?id=<?= $value['id']?>"><i class="fa fa-edit"></i> 
                                  </a>
                              </td>
                            </tr>
                          <?php }}?>
                      </tbody>
                      
                    </table>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-4">
                  </div>
                  <div class="col-sm-8">
                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                      <ul class="pagination pull-right mt0">
                        <li class="paginate_button previous disabled" id="example2_previous"><a href="#" aria-controls="example2" data-dt-idx="0" tabindex="0">Previous</a></li>
                        <li class="paginate_button active"><a href="#" aria-controls="example2" data-dt-idx="1" tabindex="0">1</a></li>
                        <li class="paginate_button next" id="example2_next"><a href="#" aria-controls="example2" data-dt-idx="7" tabindex="0">Next</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
      </div>
    </section>
</div>

