<div class="content-wrapper" ng-app="app" ng-controller="managesetting"  ng-cloak="true">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1> Add Setting</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Manage Setting</a></li>
            <li class="active"> Setting</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <!-- /.box-header -->
                    <div class="box-body">
                        <p class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</p>
                        <p class="danger" style="color:green" ng-show="successShow">{{successMsg}}</p>
                        <div class="row">
                            <div class="col-lg-4 col-sm-4 col-xs-12">
                                <div class="box-header">
                                    <h3 class="box-title"> Add Tax</h3>
                                    <p>Add Setting for product</p>
                                </div>
                            </div>
                            <div class="col-lg-8 col-sm-8 col-xs-12">
                                <div class="row">
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label> Minimum order amount</label>
                                            <input type="text" placeholder="Minimum order amount" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" class="form-control"  name="minimum_order"   ng-model="settingData.minimum_order">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Free Delivery </label>
                                            <input type="text" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder="free delivery amount" class="form-control"  name="free_delivery"   ng-model="settingData.free_delivery">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Shipping Charges</label>
                                            <input type="text" onkeyup="if (/\D/g.test(this.value)) this.value = this.value.replace(/\D/g,'')" placeholder="Shipping Charges" class="form-control"  name="shipping_charges"   ng-model="settingData.shipping_charges">
                                        </div>
                                    </div>
                                    
                                    <div class="clearfix"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="pull-right">
                            <button class="btn btn-default mr10" type="submit">Cancel</button>
                            <button class="btn btn-info" ng-click="savesetting(settingData)">Save</button>
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
<script src="<?php echo $this->basePath() . '/public/js/dashboard/managesetting.js' ?>">
</script>
<script>
    
    app.value('settingList', '<?php echo !empty($this->settingList)?json_encode($this->settingList):'';?>');
</script>