<div class="content-wrapper">
<section class="content-header">
      <h1> Manage Category</h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Systems setup</a></li>
        <li class="active"> Manage Category</li>
      </ol>
    </section>
<section class="content container-fluid">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title"> Manage Category</h3>
              <div class="pull-right"> 
                  <a href="<?php echo $this->basePath()?>/admin/dashboard/addpromotion" class="btn btn-info"> Add Category</a>
              </div>              
            </div>
            <!-- /.box-header -->            
            <div class="box-body">
                <p class="danger showMsg" style="color:green">
                    <?php
                        if(!empty($this->flashMessenger()->getMessages())){
                            $msg =  $this->flashMessenger()->getMessages();
                            echo $msg[0];
                        }
                    ?>                         
                </p>                 
              <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                <div class="row"> 
                  <div class="col-sm-6"></div>
                  <div class="col-sm-6"></div>
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    <table class="table table-bordered table-hover dataTable" id="example2" role="grid" aria-describedby="example2_info">
                      <thead>
                        <tr role="row">
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending">Category name</th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Type</th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Value</th>
						  <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Action</th>
                        </tr>
                      </thead>
                      <tbody>
                          <?php if(!empty($this->categoryList)){
                            foreach ($this->categoryList as $key => $value) {
                              ?>
                            <tr role="row" class="odd">
                                <td class=""><?= $value['promotion_name']?></td>
                              <td class=""><?= $value['type']?></td>
                              <td class="">
                                      <?php
					echo $value['value']; 
                                      ?>
                              
                              </td>
                              <td><a href="addpromotion?id=<?=$value['id']?>"><i class="fa fa-edit"></i> </a>
                                  <a href="deletepromotion?id=<?=$value['id']?>"> <i class="fa fa-trash-o"></i></a></td>
                            </tr>
                          <?php }}?>
                      </tbody>
                      
                    </table>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-4">
                    <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing <?= count($this->categoryList)?> entries</div>
                  </div>
                  <div class="col-sm-8">
                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                      <ul class="pagination pull-right mt0">
                        <li class="paginate_button previous disabled" id="example2_previous"><a href="#" aria-controls="example2" data-dt-idx="0" tabindex="0">Previous</a></li>
                        <li class="paginate_button active"><a href="#" aria-controls="example2" data-dt-idx="1" tabindex="0">1</a></li>
<!--                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="2" tabindex="0">2</a></li>
                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="3" tabindex="0">3</a></li>
                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="4" tabindex="0">4</a></li>
                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="5" tabindex="0">5</a></li>
                        <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="6" tabindex="0">6</a></li>-->
                        <li class="paginate_button next" id="example2_next"><a href="#" aria-controls="example2" data-dt-idx="7" tabindex="0">Next</a></li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
      </div>
    </section>
</div>


