<div class="content-wrapper" ng-app="app" ng-controller="ledger" ng-cloak="true" ng-init="intCall()">
    <section class="content-header">
        <h1> Manage Ledger</h1>
    </section>
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title"> Manage Ledger</h3>
                        <div class="pull-right"ng-show="showLedger"> 
                            <a href="<?php echo $this->basePath() ?>/admin/dashboard/downloadledger?merchant_id={{filter.merchant_id}}&start_date={{filter.startDate}}&end_date={{filter.endDate}}" class="btn btn-info"> Download Csv</a>
                        </div>              
                    </div>
                    <!-- /.box-header -->
                    <p class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</p>
                    <p class="danger" style="color:green" ng-show="successShow">{{successMsg}}</p>
                    <div class="col-sm-3 col-lg-3  no-rpad">
                        <div class="form-group">
                            <label>Merchant</label>
                            <select class="form-control " style="width: 100%;" tabindex="-1" aria-hidden="true" ng-model="filter.merchant_id">
                                <option selected="selected" value="">Select Merchant</option>
                                <option ng-repeat="data in merchantList" value="{{data.user_id}}">{{data.first_name}}</option>
                            </select>
                        </div>
                    </div>
                    <div class="col-sm-3 col-lg-3  no-rpad">
                        <div class="form-group">
                            <label>Start Date</label>
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <input class="datepicker" data-date-format="yyyy-mm-dd" ng-model="filter.startDate">
                            </div>
                        </div>
                    </div>

                    <div class="col-sm-3 col-lg-3  no-rpad">
                        <div class="form-group">
                            <label>End Date</label>
                            <div class="input-group">
                                <div class="input-group-addon">
                                    <i class="fa fa-calendar"></i>
                                </div>
                                <input class="datepicker" data-date-format="yyyy-mm-dd" ng-model="filter.endDate">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3 col-lg-3  no-rpad">
                        <label>&nbsp;</label>
                        <button class="btn btn-block btn-primary" type="button" ng-click="applyFilter()">Apply</button>
                    </div>

                    <div class="clearfix"></div>

                    <div class="col-sm-4 col-lg-4  no-rpad">
                        <label> Total Revenue : {{ledgerSummery.total_revenue}}</label>

                    </div>
                    <div class="col-sm-4 col-lg-4  no-rpad">
                        <label> Total Merchant Revenue : {{ledgerSummery.total_merchant_amount}}</label>

                    </div>
                    <div class="col-sm-4 col-lg-4  no-rpad">
                        <label> Total Commission : {{ledgerSummery.total_commission}}</label>

                    </div>
                    <div class="clearfix"></div>
                   <hr>
                    <p></p>
                    <div class="col-sm-4 col-lg-4  no-rpad">
                        <label> &nbsp;</label>
                        <p><b> Pay To Merchant </b><p>
                    </div>
                    <div class="col-sm-4 col-lg-4  no-rpad">
                        <label> Enter Amount</label>
                        <input type="text" placeholder="Enter amount " class="form-control"  name="name"   ng-model="paytomerchant.amount">
                    </div>
                    <div class="col-sm-4 col-lg-4  no-rpad">
                        <label>&nbsp;</label>
                        <button class="btn btn-block btn-primary" type="button" ng-click="payToMerchant()">Pay</button>
                    </div>
                     <div class="clearfix"></div>
                     <hr>
                     
                    <div class="box-body">
                        <p class="danger showMsg" style="color:green">
                            <?php
                            if (!empty($this->flashMessenger()->getMessages())) {
                                $msg = $this->flashMessenger()->getMessages();
                                echo $msg[0];
                            }
                            ?>                         
                        </p>                 
                        <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                            <div class="row"> 
                                <div class="col-sm-6"></div>
                                <div class="col-sm-6"></div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <table class="table table-bordered table-hover dataTable" id="example2" role="grid" aria-describedby="example2_info">
                                        <thead>
                                            <tr role="row">
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending">Order id</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Total Amount</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Merchant Amount</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Commission Amount</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Type</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Transection Date</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr role="row" class="odd" ng-repeat="data in ledgerList">
                                                <td class="">{{data.order_id == 0?'Cash':data.order_id}}</td>
                                                <td class="">{{data.total_amount}}</td>
                                                <td class="">{{data.merchant_amount}}</td>
                                                <td class="">{{data.commission_amount}}</td>
                                                <td class="">{{data.type}}</td>
                                                <td class="">{{data.created_date}}</td>
                                            </tr>
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    <!-- /.box-body -->
                </div>
            </div>
        </div>
    </section>
    <div style="position: fixed; top: 0; left: 0; background: rgba(0,0,0,0.3); z-index: 99999999; width: 100%; height: 100%;"  ng-show="ajaxLoadingData">
        <img style="position: absolute; top: 40%; left: 45%; width: 250px; " alt="loader" src="<?= $this->basePath() ?>/public/img/loading_cart.gif">
    </div>
</div>
<script>
    $(function () {
        $('.datepicker').datepicker();
    });
</script>
<script src="<?php echo $this->basePath() . '/public/js/dashboard/ledger.js' ?>">
</script>