<div class="content-wrapper">
    <section class="content-header">
        <h1> Manage Merchant</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Systems setup</a></li>
            <li class="active"> Manage Merchant</li>
        </ol>
    </section>
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title"> Manage Merchant</h3>
                        <div class="pull-right"> 
                            <!--a href="<?php echo $this->basePath() ?>/admin/dashboard/editmerchant" class="btn btn-info"> Add Merchant</a-->
                        </div> 
                    </div>
                    <div class="box-body">
                        <p class="danger showMsg" style="color:green">
                            <?php
                            if (!empty($this->flashMessenger()->getMessages())) {
                                $msg = $this->flashMessenger()->getMessages();
                                echo $msg[0];
                            }
                            ?>                         
                        </p>                
                        <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                            <div class="row">
                                <div class="col-sm-6"></div>
                                <div class="col-sm-6"></div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <table class="table table-bordered table-hover dataTable" id="example2" role="grid" aria-describedby="example2_info">
                                        <thead>
                                            <tr role="row">
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending"></th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending">Onwer name</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">IC Number</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Platform(s): activate to sort column ascending">Phone Numbmer</th>
                                                <th class="sorting_desc" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Engine version: activate to sort column ascending" aria-sort="descending">Email</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Address</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Company Bank name</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Company Bank Account Number</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                            if (!empty($this->marchantList)) {
                                                foreach ($this->marchantList as $key => $value) {
                                                    ?>
                                                    <tr role="row" class="odd">
                                                        <td class=""><a href="<?= !empty($this->marchantListImg[$value['id']]) ? $this->marchantListImg[$value['id']] : 'javascript:void(0)' ?>" target="blank"><img src="<?= !empty($this->marchantListImg[$value['id']]) ? $this->marchantListImg[$value['id']] : '' ?>" class="img-rounded" alt="No Image Found" style="height: 50px;width:50px;"></a></td>
                                                        <td class=""><?php if ($value['status'] == 0) { ?><i class="fa fa-close red"></i> &nbsp;<?php } ?><?= $value['first_name'] ?></td>

                                                        <td class=""><?= $value['ic_number'] ?></td>
                                                        <td class=""><?= $value['phone_number'] ?></td>
                                                        <td class="sorting_1"><?= $value['email'] ?></td>
                                                        <td><?= $value['address'] ?></td>
                                                        <td><?= $value['bank_name'] ?></td>
                                                        <td><?= $value['bank_account_number'] ?></td>
                                                        <td><a href="editmerchant?id=<?= $value['user_id'] ?>"><i class="fa fa-edit"></i> 
                                                                <i class="fa fa-trash-o"></i></a></td>
                                                    </tr>
    <?php }
} ?>
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing <?= count($this->marchantList) ?> entries</div>
                                </div>
                                <div class="col-sm-8">
                                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                                        <ul class="pagination pull-right mt0">
                                            <li class="paginate_button previous disabled" id="example2_previous"><a href="#" aria-controls="example2" data-dt-idx="0" tabindex="0">Previous</a></li>
                                            <li class="paginate_button active"><a href="#" aria-controls="example2" data-dt-idx="1" tabindex="0">1</a></li>
                                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="2" tabindex="0">2</a></li>
                                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="3" tabindex="0">3</a></li>
                                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="4" tabindex="0">4</a></li>
                                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="5" tabindex="0">5</a></li>
                                            <li class="paginate_button "><a href="#" aria-controls="example2" data-dt-idx="6" tabindex="0">6</a></li>
                                            <li class="paginate_button next" id="example2_next"><a href="#" aria-controls="example2" data-dt-idx="7" tabindex="0">Next</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>




