<div class="content-wrapper">
    <section class="content-header">
        <h1> Manage Banner</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Systems setup</a></li>
            <li class="active"> Manage Banner</li>
        </ol>
    </section>
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title"> Manage Banner</h3>
                        <div class="pull-right"> 
                            <a href="<?php echo $this->basePath() ?>/admin/dashboard/addbanner" class="btn btn-info"> Add Banner</a>
                        </div> 
                    </div>
                    <div class="box-body">
                        <p class="danger showMsg" style="color:green">
                            <?php
                            if (!empty($this->flashMessenger()->getMessages())) {
                                $msg = $this->flashMessenger()->getMessages();
                                echo $msg[0];
                            }
                            ?>                         
                        </p>                
                        <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                            <div class="row">
                                <div class="col-sm-6"></div>
                                <div class="col-sm-6"></div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <table class="table table-bordered table-hover dataTable" id="example2" role="grid" aria-describedby="example2_info">
                                        <thead>
                                            <tr role="row">
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending"></th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending">Image name</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Description</th>
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Action</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <?php
                                            if (!empty($this->bannerList)) {
                                                foreach ($this->bannerList as $key => $value) {
                                                    ?>
                                                    <tr role="row" class="odd">
                                                        <td class="">
                                                            <a href="<?= !empty($this->bannerListImg) ? $this->bannerListImg.'/'.$value['image_name'] : 'javascript:void(0)' ?>" target="blank">
                                                            <img src="<?= !empty($this->bannerListImg) ? $this->bannerListImg.'/'.$value['image_name'] : '' ?>" class="img-rounded" alt="No Image Found" style="height: 50px;width:50px;"></a>
                                                        </td>
                                                        
                                                        <td class=""><?= $value['image_name'] ?></td>
                                                        <td class=""><?= $value['description'] ?></td>
                                                        <td>
                                                            <a href="<?=$this->basePath()?>/admin/dashboard/addbanner?id=<?= $value['id']?>">
                                                               <i> Edit</i>
                                                            </a>
                                                        </td>
                                                    </tr>
    <?php }
} ?>
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Showing <?= count($this->marchantList) ?> entries</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</div>




