    <link href="<?=$this->basePath() . '/public/css/bower_components/bootstrap/dist/css/bootstrap.min.css'?>" rel="stylesheet">
    <link href="<?=$this->basePath() . '/public/css/bower_components/font-awesome/css/font-awesome.min.css'?>" rel="stylesheet">
    <link href="<?=$this->basePath() . '/public/css/bower_components/Ionicons/css/ionicons.min.css'?>" rel="stylesheet">
    <link href="<?=$this->basePath() . '/public/css/bower_components/iCheck/blue.css'?>" rel="stylesheet">
    <link href="<?=$this->basePath() . '/public/css/dist/css/style.css'?>" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</body>
</html>