<body class="hold-transition register-page">
    <script>
        $(document).ready(function(){
            $('input').iCheck({
              checkboxClass: 'icheckbox_square-blue',
              radioClass: 'iradio_square-blue',
              increaseArea: '20%' /* optional */
            });
        });
        var serverUrl ='<?php echo $GLOBALS['HTTP_SITE_ADMIN_URL']; ?>';
    </script>

    
    