<!--<form action="index" method="post">
    <input type="text" placeholder="username" name="username">
    <input type="password" placeholder="password" name="password">
    <input type="hidden" name="action" value="index"/>
    <input type="submit" name="submitbtn">
</form>-->
<div class="login-box">
  <div class="login-logo">
    <a href="index.html"><img src="<?=$this->basePath()?>/public/css/dist/img/logo-big.png" class="" alt="Logo"></a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
      <p class="login-box-msg">
                    <?php
                        if(!empty($this->flashMessenger()->getMessages())){
                            $msg =  $this->flashMessenger()->getMessages();
                            echo $msg[0];
                        }
                    ?>          
      </p> 
    <p class="login-box-msg">Sign in to start your session</p>

    <form action="index" method="post">
      <div class="form-group has-feedback">
        <input type="email" class="form-control" placeholder="Email"  name="username">
        <span class="fa fa-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
        <input type="password" class="form-control" placeholder="Password" name="password">
        <span class="fa fa-lock form-control-feedback"></span>
      </div>
      <div class="row">
        <div class="col-xs-8">
          <div class="checkbox icheck">
            <label>
              <input type="checkbox"> Remember Me
            </label>
          </div>
        </div>
        <!-- /.col -->
        <div class="col-xs-4">
          <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
        </div>
        <!-- /.col -->
      </div>
    </form>
    <a href="#">I forgot my password</a><br>
    <a href="<?php echo $this->basePath()?>/application/index/signup" class="text-center">Register a new membership</a>

  </div>
  <!-- /.login-box-body -->
</div>
<!-- /.login-box -->   