<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
        <ul class="sidebar-menu" data-widget="tree">
            <li  class="active"><a href="#"><i class="fa fa-tachometer"></i> <span>Dashboard</span></a></li>
            <li><a href="<?=$this->basePath()?>/merchant/dashboard/managestore"><i class="fa fa-home"></i> <span>Store</span></a></li>
            <li><a href="<?=$this->basePath()?>/merchant/dashboard/notification"><i class="fa fa-bell-o"></i> <span>Notification</span></a></li>
            <li><a href="<?=$this->basePath()?>/merchant/product"><i class="fa fa-suitcase"></i> <span>Manage Product</span></a></li>
            <li><a href="<?=$this->basePath()?>/merchant/product/storein"><i class="fa fa-suitcase"></i> <span>Product in Store</span></a></li>
            <li><a href="<?=$this->basePath()?>/merchant/product/stock"><i class="fa fa-suitcase"></i> <span>Product Out Of Stock</span></a></li>
            <li><a href="<?=$this->basePath()?>/merchant/product/orderlist"><i class="fa fa-shopping-basket"></i> <span>Manage Order</span></a></li>
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>