<div class="content-wrapper"  ng-app="product" ng-controller="productController">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1> Add Product</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Manage Product</a></li>
            <li class="active"> Add Product</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <form action="saveproduct" method="post" enctype="multipart/form-data">
                    <!-- /.box-header -->
                    <div class="box-body">
                        
                        <p class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</p>
                        <p class="danger" style="color:green" ng-show="successShow">{{successMsg}}</p>
                        <div class="row">
                            
                            <div class="col-lg-4 col-sm-4 col-xs-12">
                                <div class="box-header">
                                    <h3 class="box-title"> Add Product</h3>
                                    <p>Lorem ipsum is a dummy text</p>
                                </div>
                            </div>
                            <div class="col-lg-8 col-sm-8 col-xs-12">
                                <div class="row">
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Product Name</label>
                                            <input type="text" placeholder="Product Name" id="product_name"  name="product_name" class="form-control" value="<?= !empty($this->productList['product_name'])?$this->productList['product_name']:''?>">
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Category</label>
                                            <select class="form-control select2" style="width: 100%;" id="category_id" name="category_id" ng-model="productData.category_id">
                                                <option selected="selected" value="">select category</option>
                                                <option ng-repeat="data in categoryList" ng-selected="data.id ==<?=$this->productList['category_id']?>" value="{{data.id}}">{{data.category_name}}</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Promotion</label>
                                            <select class="form-control select2" style="width: 100%;" id="promotion_id" name="promotion_id" ng-model="productData.promotion_id">
                                                <option selected="selected" value="">select Promotion</option>
                                                <option ng-repeat="data in promotionList" ng-selected="data.id ==<?=$this->productList['promotion_id']?>" value="{{data.id}}">{{data.promotion_name}}</option>
                                            </select>
                                        </div>
                                    </div>                                    
                                    <div class="clearfix"></div>
                                    <div class="col-lg-12 col-sm-12 col-xs-12">
                                        <div class="form-group">
                                            <label>Item Code</label>
                                            <input type="text" placeholder="Item Code" id="item_code"  name="item_code" class="form-control" value="<?= !empty($this->productList['item_code'])?$this->productList['item_code']:''?>" maxlength="10">
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Product Description</label>
                                            <textarea class="form-control" name="product_desc" ><?= !empty($this->productList['product_desc'])?$this->productList['product_desc']:''?></textarea>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Upload</label>
                                            <input type="file"  multiple="multiple" name="product_img[]">
                                        </div>
                                        <?php
                                            $nutritionImg = '';
                                            if(!empty($this->productImage[$this->productList['id']])) {
                                                foreach($this->productImage[$this->productList['id']] as $images) {
                                                    if($images['type']=='product'){
                                                ?>
                                                        <img src="<?=$this->imageRootPath.'/'.$images['type'].'/'.$images['image_id'].'/'.$images['image_name']?>" width="50" height="50" />
                                                <?php
                                                    }else{
                                                        $nutritionImg .= "<img src=$this->imageRootPath/$images[type]/$images[image_id]/$images[image_name] width='200' height='50' />";
                                                    }
                                                }
                                            }
                                        ?>
                                    </div>
                                    <div class="clearfix"></div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Nutrition</label>
                                            <textarea class="form-control" name="nutrition" ><?= !empty($this->productList['nutrition'])?$this->productList['nutrition']:''?></textarea>
                                        </div>
                                    </div>                                    
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Nutrition image</label>
                                            <input type="file" name="nutrition_image">
                                            <?=$nutritionImg?>
                                        </div>
                                    </div>                                    
                                    <!--div id="preview"></div>
                                    <div class="col-lg-12">
                                        <div class="full-width">
<!--                                            <div class="col-sm-3 upload "> 
                                                <img alt="Photo" src="dist/img/user1-128x128.jpg" class="img-responsive"> 
                                                <a class="pull-right close" href="#"><i class="fa fa-times"></i></a> 
                                            </div>
                                        </div>
                                        <div class="clearfix">&nbsp;</div>
                                    </div-->
                                    <div class="clearfix"></div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Tax</label>
                                            <select class="form-control select2" style="width: 100%;" id="tax_id" name="tax_id" >
                                                <option selected="selected" value="">Select Tax</option>
                                                <option ng-repeat="data in taxList" ng-selected="<?= !empty($this->productList['tax_id'])?$this->productList['tax_id']:''?>" value="{{data.id}}">{{data.tax_name}} ( {{data.tax_value}} %)</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Brand Name</label>
                                            <input type="text" value="<?= !empty($this->productList['brand_name'])?$this->productList['brand_name']:''?>" name="brand_name"  placeholder="Brand name" class="form-control" >
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>                                    
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Discount Type</label>
                                            <select class="form-control select2" style="width: 100%;" id="product_discount_value" name="product_discount_type" >
                                                <option value="">Select Discount Type</option>
                                                <option  <?php if($this->productList['discount_type']== 'flat'){echo'selected';} ?> value="flat">Flat</option>
                                                <option <?php if($this->productList['discount_type']== 'percent'){echo'selected';}  ?> value="percent">Percent</option>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12">
                                        <div class="form-group">
                                            <label>Discount Value</label>
                                            <input type="text" value="<?= !empty($this->productList['discount_value'])?$this->productList['discount_value']:''?>" name="product_discount_value"  placeholder="value " class="form-control" >
                                        </div>
                                    </div>
                                    <div class="clearfix"></div>
                                    <?php 
                                    if(!empty($this->productList['atribute'])){
                                    foreach ($this->productList['atribute'] as $key => $value) {
                                        //print_r($value);die;
                                    ?>
                                    <div class=" col-lg-12" id="add-attribute">
                                        <div class="row border-top">
                                            <div class="col-lg-6 col-sm-6 col-xs-12 mt10">
                                                <div class="form-group">
                                                    <label>Attribute Name</label>
                                                    <input type="hidden" value="<?= $value['id']?>"  name="attribute_id[]">
                                                    <input type="text" value="<?= $value['name']?>" placeholder="Attribute Name" id="attribute_name_{{index}}" name="attribute_name[]" class="form-control" >
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-sm-6 col-xs-12 mt10">
                                                <div class="form-group">
                                                    <label>Unit</label>
                                                    <select class="form-control select2" style="width: 100%;" id="attribute_unit_{{index}}" name="attribute_unit[]" >
                                                        <option value="gm" <?php if($value['unit']== 'gm') echo "selected"?>>Grams</option>
                                                        <option value="liter"  <?php if($value['unit']== 'liter') echo "selected"?>>Liter</option>
                                                        <option value="kg"  <?php if($value['unit']== 'kg') echo "selected"?>>Kg</option>
                                                        <option value="ml" <?php if($value['unit']== 'ml') echo "selected"?> >ML</option>
                                                        <option value="sticks" <?php if($value['unit']== 'sticks') echo "selected"?>>Sticks</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-sm-6 col-xs-12">
                                                <div class="form-group">
                                                    <label>Quantity</label>
                                                    <input type="text" id="attribute_quantity_{{index}}" value="<?= $value['quantity']?>" name="attribute_quantity[]" placeholder="Quantity" class="form-control" >
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-sm-6 col-xs-12">
                                                <div class="form-group">
                                                    <label>Upload</label>
                                                    <input type="file" class="test file" multiple="multiple" name="attribute_img_<?=$key?>[]">
                                                </div>
                                            </div>
                                            <div class="clearfix"></div>
                                            <div class="col-lg-6 col-sm-6 col-xs-12">
                                                <div class="form-group">
                                                    <label>Commission type</label>
                                                    <select class="form-control select2"  id="attribute_commission_type_{{index}}" name="attribute_commission_type[]" >
                                                        <option value="flat" <?php if($value['commission_type'] == 'flat'){ echo "selected";}?>>flat</option>
                                                        <option value="percent" <?php if($value['commission_type'] == 'percent'){ echo "selected";}?>>percent</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-sm-6 col-xs-12">
                                                <div class="form-group">
                                                    <label>Commission value </label>
                                                    <input type="text" value='<?= !empty($value['commission_value'])?$value['commission_value']:''?>' name="attribute_commission_value[]" id="attribute_commission_value_{{index}}" placeholder="Commission value " class="form-control" >
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-sm-6 col-xs-12">
                                                <div class="form-group">
                                                    <label>Discount Type</label>
                                                    <select class="form-control select2" style="width: 100%;" id="attribute_discount_type" name="attribute_discount_type[]" >
                                                        <option selected="selected" value="">Select Discount Type</option>
                                                        <option <?php if($value['discount_type']== 'flat'){echo'selected';} ?> value="flat">Flat</option>
                                                        <option <?php if($value['discount_type']== 'percent'){echo'selected';} ?> value="percent">Percent</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-sm-6 col-xs-12">
                                                <div class="form-group">
                                                    <label>Discount Value</label>
                                                    <input type="text" value="<?= !empty($value['discount_value'])?$value['discount_value']:''?>"  name="attribute_discount_value[]"  placeholder="value " class="form-control" >
                                                </div>
                                            </div>
                                        </div>
                                        <div class="clearfix border-top">&nbsp;</div>
                                    </div>
                                    <?php } }?>
                                    
                                    <?php
                                    if (!empty($this->productList['custom_info'])) {
                                        $features = $this->productList['custom_info'];
                                        
                                        foreach ($features as $key => $value) {
                                        ?>
                                        <div class=" col-lg-12" id="add-attribute">
                                            <div class="row border-top">
                                                <div class="col-lg-6 col-sm-6 col-xs-12 mt10">
                                                    <div class="form-group">
                                                        <label>Title</label>
                                                        <input type="text"  placeholder="Title" id="attribute_name_{{index}}" name="custom_title[]" class="form-control" value="<?=$key?>">
                                                    </div>
                                                </div>

                                                <div class="col-lg-6 col-sm-6 col-xs-12">
                                                    <div class="form-group">
                                                        <label>Title Description </label>
                                                        <textarea class="form-control" name="custom_dis[]" ><?= !empty($value) ? $value : '' ?></textarea>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="clearfix border-top">&nbsp;</div>
                                        </div>
                                        <?php
                                    }
                                    }
                                    ?>
                                    <div class="clearfix"></div>
                                    
                                    <span ng-repeat="index in indexVal">
                                    <div class=" col-lg-12" id="add-attribute" ng-show="showAttr">
                                        <div class="row border-top">
                                            <div class="col-lg-6 col-sm-6 col-xs-12 mt10">
                                                <div class="form-group">
                                                    <label>Attribute Name</label>
                                                    <input type="hidden" value=""  name="attribute_id[]">
                                                    <input type="text" value="" placeholder="Attribute Name" id="attribute_name_{{index}}" name="attribute_name[]" class="form-control" >
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-sm-6 col-xs-12 mt10">
                                                <div class="form-group">
                                                    <label>Unit</label>
                                                    <select class="form-control select2" style="width: 100%;" id="attribute_unit_{{index}}" name="attribute_unit[]" >
                                                        <option value="grams" selected>Grams</option>
                                                        <option value="liter" >Liter</option>
                                                        <option value="kg">Kg</option>
                                                        <option value="ml">ML</option>
                                                        <option value="sticks">Sticks</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-sm-6 col-xs-12">
                                                <div class="form-group">
                                                    <label>Quantity</label>
                                                    <input type="text" id="attribute_quantity_{{index}}" value="" name="attribute_quantity[]" placeholder="Quantity" class="form-control" >
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-sm-6 col-xs-12">
                                                <div class="form-group">
                                                    <label>Upload</label>
                                                    <input type="file" class="test file" multiple="multiple" name="attribute_img_{{index}}[]">
                                                </div>
                                            </div>
                                            <div class="clearfix"></div>
                                            <div class="col-lg-6 col-sm-6 col-xs-12">
                                                <div class="form-group">
                                                    <label>Commission type</label>
                                                    <select class="form-control select2"  id="attribute_commission_type_{{index}}" name="attribute_commission_type[]" >
                                                        <option value="flat" selected>flat</option>
                                                        <option value="percent" >percent</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-sm-6 col-xs-12">
                                                <div class="form-group">
                                                    <label>Commission value </label>
                                                    <input type="text" name="attribute_commission_value[]" id="attribute_commission_value_{{index}}" placeholder="Commission value " class="form-control" >
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-sm-6 col-xs-12">
                                                <div class="form-group">
                                                    <label>Discount Type</label>
                                                    <select class="form-control select2" style="width: 100%;" id="attribute_discount_type" name="attribute_discount_type[]" >
                                                        <option selected="selected" value="">Select Discount Type</option>
                                                        <option  value="flat">Flat</option>
                                                        <option  value="percent">Percent</option>
                                                    </select>
                                                </div>
                                            </div>
                                            <div class="col-lg-6 col-sm-6 col-xs-12">
                                                <div class="form-group">
                                                    <label>Discount Value</label>
                                                    <input type="text"  name="attribute_discount_value[]"  placeholder="value " class="form-control" >
                                                </div>
                                            </div>
                                           
                                            
                                        </div>
                                        <div class="clearfix border-top">&nbsp;</div>
                                    </div>
                                    </span>    
                                    <div class="clearfix"></div>
                                    
                                    <span ng-repeat="index in indexValDis">
                                    <div class=" col-lg-12" id="add-attribute" ng-show="showAttrDis">
                                        <div class="row border-top">
                                            <div class="col-lg-6 col-sm-6 col-xs-12 mt10">
                                                <div class="form-group">
                                                    <label>Title</label>
                                                    <input type="text" value="" placeholder="Title" id="attribute_name_{{index}}" name="custom_title[]" class="form-control" >
                                                </div>
                                            </div>
                                            
                                            <div class="col-lg-6 col-sm-6 col-xs-12">
                                                <div class="form-group">
                                                    <label>Title Description </label>
                                                    <textarea class="form-control" name="custom_dis[]" ></textarea>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="clearfix border-top">&nbsp;</div>
                                    </div>
                                    </span>    
                                    <div class="clearfix"></div>

                                    <div class="col-lg-6 col-sm-6 col-xs-12  pull-right">
                                        <button class="btn btn-default pull-right" type="button" id="show-attribute" ng-click="showAttrDiv()"><i class="fa fa-plus"></i> Add Attribute</button>
                                    </div>
                                    <div class="col-lg-6 col-sm-6 col-xs-12  pull-right">
                                        <button class="btn btn-default pull-right" type="button" id="show-attribute" ng-click="showAttrDivDis()"><i class="fa fa-plus"></i> Add Custom Fields </button>
                                    </div>
                                </div>
                            </div>
                            
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="col-lg-4 col-sm-4 col-xs-12">
                                        </div>
                        <div class="col-lg-5 col-sm-5 col-xs-12">
                            <div class="form-group">
                                <label>Hot Deals And New Offers</label>
                                <div class="clearfix"></div>
                                <label class="mr10">Hot Deals</label>					
                                <input type="checkbox" name="hotdeals" value="1" class="minimal" <?php if(!empty($this->productList['hotdeals'])){?>checked="checked" <?php }?>>
                                <label class="mr10 ml10">New Offers</label>					
                                <input type="checkbox" name="offers" value="1" class="minimal" <?php if(!empty($this->productList['offers'])){?>checked="checked" <?php }?>>
                                <label class="mr10 ml10">New Arrival</label>					
                                <input type="checkbox" name="new_arrival" value="1" class="minimal" <?php if(!empty($this->productList['new_arrival'])){?>checked="checked" <?php }?>>                                
                            </div>
                        </div>                        
                        <div class="col-lg-3 col-sm-3 col-xs-12">
                            <div class="form-group">
                                <label>Product Status</label>
                                <div class="clearfix"></div>
                                <label class="mr10">Active</label>					
                                <input type="radio" name="status" value="1" class="minimal" <?php if(!empty($this->productList['status'])){?>checked="checked" <?php }?>>

                                <label class="mr10 ml10">Inactive</label>					
                                <input type="radio" name="status" value="0" class="minimal" <?php if(empty($this->productList['status'])){?>checked="checked" <?php }?>>
                            </div>
                        </div>	
                        <input type="hidden" value="{{index}}" id="index" name="index">
                        <input type="hidden" value="<?= $this->productList['id']?>" id="id" name="id">
                        <div class="pull-right">
                            <a href="<?php echo $this->basePath() ?>/admin/product/index" class="btn btn-info"> Cancel</a>
                            <button class="btn btn-info" type="submit" onclick="return checkform()">Save</button>
                        </div>
                    </div>
                    <!-- /.box-body -->
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
<script src="<?php echo $this->basePath() . '/public/js/dashboard/addproduct.js' ?>"></script>
<script>
    $(function () {
        // Multiple images preview in browser
        var imagesPreview = function (input, placeToInsertImagePreview) {

            if (input.files) {
                var filesAmount = input.files.length;

                for (i = 0; i < filesAmount; i++) {
                    var reader = new FileReader();

                    reader.onload = function (event) {
                        $($.parseHTML('<img>')).attr('src', event.target.result).appendTo(placeToInsertImagePreview);
                    }

                    reader.readAsDataURL(input.files[i]);
                }
            }

        };

        $('#gallery-photo-add').on('change', function () {
            imagesPreview(this, 'p.gallery');
        });
    });
</script>
<script>
    app.value('productList', '<?php echo !empty($this->productList['atribute'])?count($this->productList['atribute']):'';?>');
</script>
<?php

//echo count($this->productList['atribute']);die;
        ?>
