<?php
$html = '<div class="content-wrapper">
<section class="content container-fluid">
      <div class="row">
        <div class="col-xs-12">
          <div class="box">
            <div class="box-header">
              <h3 class="box-title"> Order Details</h3>
             
            </div>          
            <div class="box-body">
                                
              <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                <div class="row"> 
                  <div class="col-sm-6"></div>
                  <div class="col-sm-6"></div>
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    <table class="table table-bordered table-hover dataTable" id="example2" role="grid" aria-describedby="example2_info">
                      <thead>
                        <tr role="row">
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending">Product Name</th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending"> Quantity </th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Product amount</th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Product Des.</th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending">Commission amount</th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Browser: activate to sort column ascending">Discount amount</th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Tax amount</th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="CSS grade: activate to sort column ascending">Shipping address</th>
                          <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending">Product Image</th>
                        </tr>
                      </thead>
                      <tbody>';?>
                            <?php
                                $csvData = array();
                                $csvData[0]['product_name'] = 'Product Name';
                                $csvData[0]['number_of_item'] = 'Quantity';
                                $csvData[0]['amount'] = 'Amount';
                                //echo "<pre>";print_r($this->productDetails);die;
                                if(!empty($this->productDetails)){
                                    foreach ($this->productDetails['data'] as $key => $value) {
                                        foreach ($value['orderitem'] as $keys => $orderitem) {
                                            $counter++;
                                            $csvData[$counter]['product_name'] = $orderitem['product_dump']['product_details']['product_name'];
                                            $csvData[$counter]['number_of_item'] = $orderitem['number_of_item'];
                                            $csvData[$counter]['amount'] = $orderitem['amount'];
                                            $imgpath = $this->productDetails['imageRootPath'].'/'.$orderitem['product_dump']['product_image_data'][0]['type'].'/'.$orderitem['product_dump']['product_details']['product_id'].'/'.$orderitem['product_dump']['product_image_data'][0]['image_name'];

                            ?>

                             <?php
                             $html .='<tr role="row" class="odd">
                                        <td class="">'.$orderitem['product_dump']['product_details']['product_name'].'
                                        </td>
                                        <td>'.$orderitem['number_of_item'].'
                                        </td>
                                        <td class="">'.$orderitem['amount'].'</td>
                                        <td class="">'.$orderitem['product_dump']['product_details']['product_desc'].'</td>
                                        <td class="">'.$orderitem['commission_amount'].'</td>
                                        <td class="">'.$orderitem['discount_amount'].'</td>
                                        <td class="">'.$orderitem['tax_amount'].'</td>
                                        <td class="">'
                                                    .$this->productDetails['shipping_address_list'][$value['order_details']['shipping_address_id']]['house_number'].' '
                                                    .$this->productDetails['shipping_address_list'][$value['order_details']['shipping_address_id']]['street_detail'].' '
                                                    .$this->productDetails['shipping_address_list'][$value['order_details']['shipping_address_id']]['area'].' '
                                                    .$this->productDetails['shipping_address_list'][$value['order_details']['shipping_address_id']]['city_name'].' '
                                                    .$this->productDetails['shipping_address_list'][$value['order_details']['shipping_address_id']]['zipcode'];
                                        $html .='</td>
                                        <td class=""><img src="<?=$imgpath?>"  height="60" width="60"></td>
                                    </tr>';          
                                    }
                                }
                            }
                            $html .='
                      </tbody>
                      
                    </table>
                  </div>
                </div>
              </div>
            </div>
            <!-- /.box-body -->
          </div>
        </div>
      </div>
    </section>
</div>';
                                    
                                    echo $html;
                                    ?>
