

<form onsubmit="return validateFormData('addPriceForm');" id="addPriceForm" method="post" action="<?php echo $GLOBALS['HTTP_SITE_ADMIN_URL']."dashboard/pricesave"?>">
  
    <input type="text" id="coupon_code" name="coupon_code" placeholder="coupon code" validation="blank">
  
  <input type="text" id="price" name="price"  validation="Number" placeholder="price">
  <input type="text" id="activation_date" name="activation_date" validation="blank" placeholder="activation date">
  
   <input type="text" id="expiry_date" name="expiry_date" validation="blank" placeholder="expiry date">
   
 <select>
  <option value="volvo">one time </option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>     
          <input type="submit" value="save"/>
      
</form>

