<section>
    <div class="container">
        <div class="left"> <!--main.css line 108 to 113 -->
            <h2>YOUR CART</h2>
                
        </div>
        <a href="" class="btn btn-primary btn-lg back" >Back To Products</a><!--main.css line 114 to 117 -->
        <div class="table-responsive">          
            <table class="table table-condensed table-hover table-bordered">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>ITEM</th>
                        <th>DISCRIPTION</th>
                        <th>PRICE</th>
                        <th>REMOVE</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>HireApplicants service package</td>
                        <td>Monthly Subscription</td>
                        <td></td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>HireApplicants service package</td>
                        <td>Monthly Subscription</td>
                        <td></td>
                        <td></td>
                    </tr>
                </tbody>
            </table>
        </div>
        <div class="left">
            <form>
                <div class="form-group">
                    <input type="text" class="form-control coupon" id="usr" placeholder="Enter Coupon Code"><!--main.css line 118 to 120 -->
                    <button type="submit" name="submit" class="btn btn-primary btn-lg coupon1" required="required">Apply Coupon</button>
                </div>
            </form>


        </div>
        <div class="checkout">
            <a href="" class="btn btn-primary btn-lg back">Proceed To CheckOut</a>
        </div>
        <div class="left">
            <h2>CART TOTAL</h2>
            <div class="table-responsive">          
                <table class="table table-condensed table-hover table-bordered">
                    <thead>
                        <tr>

                            <th>DISCRIPTION</th>
                            <th>PRICE</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>

                            <td>Cart SubTotal</td>
                            <td></td>

                        </tr>
                        <tr>

                            <td>Discount</td>
                            <td></td>

                        </tr>
                        <tr>

                            <td>Order Total</td>
                            <td></td>

                        </tr>
                    </tbody>
                </table>

            </div>



        </div>

    </div><!--/container-->
</section><!--/pricing-page-->
<link href="<?=$this->basePath() . '/public/css/companycss/cart_checkout.css?v=1'?>" rel="stylesheet">
