<div class="content-wrapper">
    <section class="content-header">
        <h1> Manage Product</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Systems setup</a></li>
            <li class="active"> Manage Product</li>
        </ol>
    </section>
    <section class="content container-fluid">
        <div class="row" ng-app="notification" ng-controller="notificationController" ng-cloak="true">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title"> Manage Notification</h3>
                    </div>
                    <div class=" col-lg-12" id="add-attribute" style="display: none;">
                        <div class="full-width pull-left border-top">&nbsp;</div>
                    </div>
                    <div class="clearfix"></div>

                    <div class="box-body">                        
                        <div id="example2_wrapper" class="dataTables_wrapper form-inline dt-bootstrap">
                            <div class="row">
                                <div class="col-sm-6"></div>
                                <div class="col-sm-6"></div>
                            </div>
                            <div class="row">
                                <div class="col-sm-12">
                                    <table class="table table-bordered table-hover dataTable" id="example2" role="grid" aria-describedby="example2_info">
                                        <thead>
                                            <tr role="row">
                                                <th class="sorting" tabindex="0" aria-controls="example2" rowspan="1" colspan="1" aria-label="Rendering engine: activate to sort column ascending">Notification</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr role="row" class="odd" ng-repeat="data in notificationList">
                                                <td> {{data.msg}}</td>
                                            </tr>
                                            
                                        </tbody>

                                    </table>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="dataTables_info" id="example2_info" role="status" aria-live="polite">Total {{numberOfRecord}} entries</div>
                                </div>
                                <div class="col-sm-8">
                                    <div class="dataTables_paginate paging_simple_numbers" id="example2_paginate">
                                        <pagination  class="pagination pull-right mt0" ng-model="currentPage" total-items="numberOfRecord" max-size="3" boundary-links="true" ng-click="selectPage(currentPage)"></pagination>
                                    </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <!-- /.box-body -->
                </div>
            </div>
            <div style="position: fixed; top: 0; left: 0; background: rgba(0,0,0,0.3); z-index: 99999999; width: 100%; height: 100%;"  ng-show="ajaxLoadingData">
                <img style="position: absolute; top: 40%; left: 45%; width: 250px; " alt="loader" src="<?=$this->basePath()?>/public/img/loading_cart.gif">
            </div>
        </div>
    </section>
</div>
<script>
    var PAGE_COUNT = 5;
    var PAGING_GAP = 3;
</script>
<script src="<?php echo $this->basePath() . '/public/js/merchant/dashboard/managenotification.js' ?>"></script>