
    <section class="pricing-page" ng-app="service" ng-controller="packagelistController">
        <div class="container">
            <div class="center">  
                <h2>HireApplicants Service Package Subscription </h2>
                <p class="lead">You can choose any of our service package <br>And enjoy our service.</p>
            </div>  
            <div class="pricing-area text-center">
                <div class="row">
                    <div class="col-sm-3 plan price-four wow fadeInDown animated">
                        <ul>
                            <li class="heading-four">
                                <h1>Start Up</h1>
                                <span>$6 For 1 Month</span>
                            </li>
                            <li>1 Month Subscription</li>
                            <li>24/7 Support</li>
                            <li class="plan-action">
                                <a href="" class="btn btn-primary">Add To Cart</a>
                            </li>
                        </ul>
                    </div>
					<div class="col-sm-3 plan price-one wow fadeInDown animated" >
                        <ul>
                            <li class="heading-one">
                                <h1>Basic</h1>
                                <span>$6 For 3 Month</span>
                            </li>
                            <li>3 Month Subscription</li>
                            <li>24/7 Support</li>
                            <li class="plan-action">
                                <a href="" class="btn btn-primary">Add To Cart</a>
                            </li>
                        </ul>
                    </div>

                    <div class="col-sm-3 plan price-two wow fadeInDown animated" >
                        <ul>
                            <li class="heading-two">
                                <h1>Standerd</h1>
                                <span>$12 For 6 Month</span>
                            </li>
                            <li>6 Months Subscription</li>
                            <li>24/7 Support</li>
                            <li class="plan-action">
                                <a href="" class="btn btn-primary">Add To Cart</a>
                            </li>
                        </ul>
                    </div>

                    <div class="col-sm-3 plan price-three wow fadeInDown animated">
                        <img src="images/ribon_one.png">
                        <ul>
                            <li class="heading-three">
                                <h1>Premium</h1>
                                <span>$24 For 12 Month</span>
                            </li>
                            <li>12 Months Subscription</li>
                            <li>24/7 Support</li>
                            <li class="plan-action">
                                <a href="" class="btn btn-primary">Add To Cart</a>
                            </li>
                        </ul>
                    </div>
<div class="center">  
                <h2>SMS Service Subscription</h2>
                <p class="lead">You can choose any of our service package for SMS <br>And enjoy our service.</p>
            </div> 
                    <div class="col-sm-3 plan price-four wow fadeInDown animated">
                        <ul>
                            <li class="heading-four">
                                <h1>Start Up</h1>
                                <span>$6 For 200 SMS</span>
                            </li>
                            <li>For Start Communication</li>
                            <li>24/7 Support</li>
                            <li class="plan-action">
                                <a href="" class="btn btn-primary">Add To Cart</a>
                            </li>
                        </ul>
                    </div>
					<div class="col-sm-3 plan price-one wow fadeInDown animated" >
                        <ul>
                            <li class="heading-one">
                                <h1>Basic</h1>
                                <span>$6 For 500 SMS</span>
                            </li>
                            <li>For Better Service</li>
                            <li>24/7 Support</li>
                            <li class="plan-action">
                                <a href="" class="btn btn-primary">Add To Cart</a>
                            </li>
                        </ul>
                    </div>

                    <div class="col-sm-3 plan price-two wow fadeInDown animated" >
                        <ul>
                            <li class="heading-two">
                                <h1>Standerd</h1>
                                <span>$12 For 1000 SMS</span>
                            </li>
                            <li>For Interupted Service</li>
                            <li>24/7 Support</li>
                            <li class="plan-action">
                                <a href="" class="btn btn-primary">Add To Cart</a>
                            </li>
                        </ul>
                    </div>

                    <div class="col-sm-3 plan price-three wow fadeInDown animated">
                        <img src="images/ribon_one.png">
                        <ul>
                            <li class="heading-three">
                                <h1>Premium</h1>
                                <span>$24 For 1500 SMS</span>
                            </li>
                            <li>For Long Service</li>
                            <li>24/7 Support</li>
                            <li class="plan-action">
                                <a href="" class="btn btn-primary">Add To Cart</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div><!--/pricing-area-->
        </div><!--/container-->
    </section><!--/pricing-page-->
   
<script src="<?=$this->basePath() . '/public/js/companyjs/service.js'?>"></script>