<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu" data-widget="tree">
            <li  class="active"><a href="#"><i class="fa fa-tachometer"></i> <span>Dashboard</span></a></li>
            <li class="treeview"> <a href="#"><i class="fa fa-link"></i> <span>System Setup</span> <span class="pull-right-container"> <i class="fa fa-angle-left pull-right"></i> </span> </a>
                <ul class="treeview-menu">
                    <li><a href="<?=$this->basePath()?>/admin/dashboard/userlist"><i class="fa fa-users"></i> <span>User</span></a></li>
                    <li><a href="<?=$this->basePath()?>/admin/rider"><i class="fa fa-motorcycle"></i> <span>Riders</span></a></li>
                    <li><a href="<?=$this->basePath()?>/admin/dashboard/location"><i class="fa fa-home"></i> <span>Area Location</span></a></li>
                    <li><a href="<?=$this->basePath()?>/admin/dashboard/managemerchant"><i class="fa fa-bank"></i> <span>Merchant</span></a></li>
                    <li><a href="<?=$this->basePath()?>/admin/dashboard/managepromotion"><i class="fa fa-star"></i> <span>Manage Promotion</span></a></li>
                    <li><a href="<?=$this->basePath()?>/admin/dashboard/managecategory"><i class="fa fa-star"></i> <span>Product Category</span></a></li>
                    <li><a href="<?=$this->basePath()?>/admin/dashboard/managetimeslot"><i class="fa fa-times-rectangle-o"></i> <span>Delivery Time Slot</span></a></li>
                    <li><a href="<?=$this->basePath()?>/admin/dashboard/managetax"><i class="fa fa-times-rectangle-o"></i> <span>Manage Tax</span></a></li>
                    <li><a href="<?=$this->basePath()?>/admin/dashboard/managecity"><i class="fa fa-times-rectangle-o"></i> <span>Manage City</span></a></li>
                    <li><a href="<?=$this->basePath()?>/admin/dashboard/managebanner"><i class="fa fa-times-rectangle-o"></i> <span>Manage Banner</span></a></li>
                    <li><a href="<?=$this->basePath()?>/admin/dashboard/restrictedlocation"><i class="fa fa-times-rectangle-o"></i> <span>Restricted Location</span></a></li>
                </ul>
            </li>
            <li><a href="<?=$this->basePath()?>/admin/dashboard/notification"><i class="fa fa-bell-o"></i> <span>Notification</span></a></li>
            <li><a href="<?=$this->basePath()?>/admin/product"><i class="fa fa-suitcase"></i> <span>Manage Product</span></a></li>
            <li><a href="<?=$this->basePath()?>/admin/product/stock"><i class="fa fa-suitcase"></i> <span>Product Out Of Stock</span></a></li>            
            <li><a href="<?=$this->basePath()?>/admin/product/orderlist"><i class="fa fa-shopping-basket"></i> <span>Manage Order</span></a></li>
            <li><a href="<?=$this->basePath()?>/admin/dashboard/manageledger"><i class="fa fa-money"></i> <span>Manage Ledger</span></a></li>
            <li><a href="<?=$this->basePath()?>/admin/dashboard/managesetting"><i class="fa fa-cog fa-fw"></i> <span>Setting</span></a></li>
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>
