<div class="content-wrapper"  ng-app="app" ng-controller="managerider">
    <!-- Content Header (Page header) -->
    <section class="content-header">
        <h1> Add Rider</h1>
        <ol class="breadcrumb">
            <li><a href="#"><i class="fa fa-dashboard"></i> Manage Rider</a></li>
            <li class="active"> Add Rider</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content container-fluid">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <form>
                        <!-- /.box-header -->
                        <div class="box-body">

                            <p class="danger" style="color:red" ng-show="errorShow">{{errorMsg}}</p>
                            <p class="danger" style="color:green" ng-show="successShow">{{successMsg}}</p>
                            <div class="row">

                                <div class="col-lg-4 col-sm-4 col-xs-12">
                                    <div class="box-header">
                                        <h3 class="box-title"> Add Rider</h3>
                                        <p></p>
                                    </div>
                                </div>
                                <div class="col-lg-8 col-sm-8 col-xs-12">
                                    <div class="row">
                                        <div class="col-lg-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label>Rider Name</label>
                                                <input type="text" placeholder="Rider Name" id="rider_name"  name="rider_name" class="form-control" ng-model="riderData.name">
                                            </div>
                                        </div>
                                        <div class="col-lg-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label>Rider Email</label>
                                                <input type="text" placeholder="Rider Email" id="rider_email"  name="rider_name" class="form-control" ng-model="riderData.email">
                                            </div>
                                        </div> 
                                        <div class="col-lg-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label>Rider Mobile Number</label>
                                                <input type="text" placeholder="Rider Mobile Number" id="rider_mobile"  name="rider_mobile" class="form-control" ng-model="riderData.mobile_number">
                                            </div>
                                        </div>                                        
                                        <div class="col-lg-6 col-sm-6 col-xs-12" ng-if="riderId==0 || (riderId>0 && resetPassword)">
                                            <div class="form-group">
                                                <label>Rider Password</label>
                                                <input type="password" placeholder="Rider Password" id="rider_password"  name="rider_password" class="form-control" ng-model="riderData.password">
                                            </div>
                                        </div>  
                                        <div class="col-lg-6 col-sm-6 col-xs-12" ng-if="riderId==0 || (riderId>0 && resetPassword)">
                                            <div class="form-group">
                                                <label>Confirm Password</label>
                                                <input type="password" placeholder="Rider Password" id="confirm_password"  name="confirm_password" class="form-control" ng-model="riderData.confirm_password">
                                            </div>
                                        </div>                                        
                                        <div class="col-lg-6 col-sm-6 col-xs-12">
                                            <div class="form-group">
                                                <label>Select Location</label>
                                                <select class="form-control select2" style="width: 100%;" id="location_id" name="location_id" ng-model="riderData.location_id">
                                                    <option selected="selected" value="">select Location Market</option>
                                                    <?php
                                                    foreach($this->locationList as $key=>$location) {
                                                        echo "<option value='$key'>$location[address]</option>";
                                                    }
                                                    ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-lg-6 col-sm-12 col-xs-12">
                                            <div class="form-group">
                                                <label>Status</label>
                                                <div class="clearfix"></div>
                                                <label class="mr10">Active</label>					
                                                <input type="radio" value="1" name="status" class="minimal" ng-model="riderData.status">

                                                <label class="mr10 ml10">Inactive</label>					
                                                <input type="radio" value="0" name="status" class="minimal"  ng-model="riderData.status">
                                            </div>
                                        </div>                                        
                                    </div>
                                </div>

                            </div>
                        </div>
                        <div class="box-footer">
                            <div class="pull-right">
                                <a href="<?php echo $this->basePath() ?>/admin/rider/index" class="btn btn-info"> Cancel</a>
                                <button class="btn btn-info" ng-click="saveRider(riderData)">Save</button>
                            </div>
                        </div>
                        <!-- /.box-body -->
                    </form>
                </div>
            </div>
        </div>
    </section>
    <!-- /.content -->
</div>
<script>
    var app = angular.module('app', []);
    app.value('riderId', '<?php echo isset($this->params['id']) ? $this->params['id'] : 0 ?>');
    app.value('riderList', '0');
    app.value('resetPassword', '<?php echo isset($this->params['resetpassword']) ? $this->params['resetpassword'] : 0 ?>');
    
    
    
</script>
<script src="<?php echo $this->basePath() . '/public/js/rider/rider.js' ?>"></script>
