<?php 
echo $this->doctype(); ?>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title></title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
    <?php echo $this->headScript()
        ->prependFile($this->basePath().'/public/css/bower_components/iCheck/icheck.min.js')
        ->prependFile($this->basePath().'/public/css/bower_components/bootstrap/dist/js/bootstrap.min.js')
        ->prependFile($this->basePath().'/public/css/bower_components/jquery/dist/jquery.min.js')
        ->prependFile($this->basePath().'/public/js/angular.min.js')
        ->prependFile($this->basePath().'/public/js/jquery.min.js');
    ?>  
</head>   
    <?php 
    echo $this->partial('layout/default/header');
    ?>
            <?php 
            echo $this->content; ?>
            <?php
    echo $this->partial('layout/default/footer');
    ?>        
               
        <?php echo $this->inlineScript() ?>
<script>
            var serverAppUrl = '<?php echo $GLOBALS['SITE_APP_URL']; ?>';
            var serverAdminApp = '<?php echo $GLOBALS['HTTP_SITE_ADMIN_URL']; ?>';
</script>
 
</html>
