<?php 
echo $this->doctype(); ?>

<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <title>AFRO BASKETS | Registration Page</title>
  <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
<?php 
echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))?>

        <!-- Scripts -->
        <?php 
        echo $this->headScript()
            ->prependFile($this->basePath().'/public/js/common.js')
            ->prependFile($this->basePath().'/public/js/ui-bootstrap-tpls-0.12.1.min.js')                
            ->prependFile($this->basePath().'/public/css/dist/js/adminlte.min.js')    
            ->prependFile($this->basePath().'/public/css/bower_components/jquery-slimscroll/jquery.slimscroll.min.js')
            ->prependFile($this->basePath().'/public/css/bower_components/jquery-slimscroll/jquery.slimscroll.min.js')
            ->prependFile($this->basePath().'/public/css/bower_components/bootstrap-datepicker/dist/js/bootstrap-datepicker.min.js')
            ->prependFile($this->basePath().'/public/css/bower_components/bootstrap-daterangepicker/daterangepicker.js')
            ->prependFile($this->basePath().'/public/css/bower_components/moment/min/moment.min.js')
            ->prependFile($this->basePath().'/public/css/bower_components/select2/dist/js/select2.full.min.js')
            ->prependFile($this->basePath().'/public/css/bower_components/iCheck/icheck.min.js')
            ->prependFile($this->basePath().'/public/css/bower_components/bootstrap/dist/js/bootstrap.min.js')
            ->prependFile($this->basePath().'/public/js/angular.min.js')
            ->prependFile($this->basePath().'/public/css/bower_components/jquery/dist/jquery.min.js');
        ; ?>
    </head>  
</head>   
    <?php 
    echo $this->partial('layout/merchant/header');
    ?>
            <?php 
            echo $this->content; ?>
            <?php
    echo $this->partial('layout/merchant/footer');
    ?>        
               
        <?php echo $this->inlineScript() ?>
<script>
            var serverAppUrl = '<?php echo $GLOBALS['SITE_APP_URL']; ?>';
            var serverMerchantApp = '<?php echo $GLOBALS['HTTP_SITE_MERCHANT_URL']; ?>';
</script>
 
</html>
